REM BLINKY2BRAM_UCF.bat wmh 2015-02-18 : generates a compile-time .ucf file for the BRAMs containing the software for the 'BLINKY' mc8051-FPGA implementation example 
REM updated 2015-02-18 to use the Windows compatible hex2mem.exe executable generated by mingw2 gcc
REM
REM Edit path information below for compatibility on your system 
REM

REM  copy the .hex file of the BLINKY example generated by the Keil compiler into the local directory
	copy ..\8051_code\BLINKY.hex BLINKY.hex
REM  convert Blinky.hex file into Blinky.memh file to be used by the Xilinx tools
	hex2readmemh BLINKY

	pause

